server:
  port: 1346
spring:
  application:
    name: micro-service-share-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chensir2896/micro-service-share-config
          username: *****@163.com
          password: *****
eureka:
  client:
    service-url:
      defaultZone: http://microservice-eureka-server-7001:7001/eureka/

