server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机版
#      defaultZone: http://microservice-eureka-server-7002:7002/eureka/,http://microservice-eureka-server-7003:7003/eureka/  #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
    register-with-eureka: false  #是否将自己这个服务注册到EurekaServer中  默认true  此服务为Server  所以为false,本身就是注册中心，false代表不向注册中农信注册自己
    fetch-registry: false         #注册中心职责是维护服务示例，不需要去检索服务，所以设置成false
  instance:
    hostname: microservice-eureka-server-7001
spring:
  application:
    name: microservice-eureka-server






