server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://microservice-eureka-server-7001:7001/eureka/,http://microservice-eureka-server-7003:7003/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: microservice-eureka-server-7002
spring:
  application:
    name: microservice-eureka-server
